/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tnjewkkoswganffxgydg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuamV3a2tvc3dnYW5mZnhneWRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY3NDI4OTMsImV4cCI6MjA4MjMxODg5M30.hCU8UJg9pEcQMg8dJ-GEE0uXD4unlfn8_UdkI0-cFyM"